### ISSUE TITLE
mongo

### ISSUE THREAD

**Issue by cbaakman** [cmbi/whynot#12]
A new branch was recently created: https://github.com/cmbi/whynot/tree/mongo

It's an experiment where postgresql is replaced by mongodb and java is replaced by python.

An advantage is that changes to the database are faster, sessions don't expire and some webpages load faster.
However, the restful services and pages that process large quantities of data, take more time.

Maybe python/mongodb is just too slow or maybe there are still some tricks possible to speed it up.

**Comment by jonblack** [comment]
Agreed.
