### ISSUE TITLE
soap

### ISSUE THREAD

**Issue by cbaakman** [cmbi/whynot#13]
The whynot website was originally created to have a SOAP webservice (http://www.cmbi.ru.nl/WHY_NOT2/webservice/ws?wsdl). It offers the same features as the restful webservice (http://www.cmbi.ru.nl/WHY_NOT2/webservice/rs?_wadl).

I doubt people are still using the SOAP, maybe we should consider not to include it in the next whynot version.

**Comment by jonblack** [comment]
Agreed.
