### ISSUE TITLE
[EPIC] Clarify project boundaries

### ISSUE THREAD

**Issue by jonblack** [cmbi/whynot#15]
# Features

There are two distinct features of this project:
1. Serve HTML over The Internet so users can see which files are missing, and their reason, from various databanks
2. Update the mongo database when databanks change. This is mostly controlled via the databanks scripts which we store in another project.

The problems with this are:
- This project is not responsible for updating its own data.
- The frontend, frontend and databanks script (indirectly) all access the same database. This increases coupling and could make data integrity issues difficult to find.
# Ideas

Split this project into the following separate services:
- frontend: only responsible for serving HTML to view data. It doesn't talk to the database, but instead to a backend REST server, to get data that it needs to display.
- backend: provides a REST API allowing access to whynot data, and runs a separate background Process to update the database. The background process should run independently of the databanks script mentioned above.

When thinking about the backend I wondered if it should be two separate services itself, where one just serves a REST API and the other updates the database. The problem with this is that you then have two services that operate on the same database. Perhaps it's not so bad since one reads and the other writes. I think it's still something to consider.

Languages like go and rust (although its http library is not stable as far as I know) would be a great option for the backend, particularly the crawling and annotating part. Frameworks like EmberJS would be great for the frontend.

This issue is a big rewrite so don't run off with it blindly. It needs some serious though.

**Comment by cbaakman** [comment]
The whynot web application already provides a restful service. Though it's not used much.

**Comment by jonblack** [comment]
A first pass has been made where the update process is included in the docker container with the frontend, which also contains a small API.
