### ISSUE TITLE
Remove dsspcmbi

### ISSUE THREAD

**Issue by jonblack** [cmbi/whynot#18]
The repository has the executable `scripts/dsspcmbi` which is used to determine why a `DSSP` or `DSSP_REDO` file doesn't exist.

Executables shouldn't be included in version control. If whynot depends on an external program, we should be that into the deployment environment.

What source was used to compile this executable?

**Comment by cbaakman** [comment]
I'm afraid that this executable was compiled before my time here. So I don't have the source code. However, we might be able to use xssp's executable instead and change the whynot code.

**Comment by touwwouter** [comment]
If I remember correctly, this executable gives informative error messages that are used for whynot comments (in contrast to the current xssp executable).

You should check a few entries with whynot dssp comments. Can you change xssp accordingly?

Op 9 nov. 2016 om 10:15 heeft cbaakman <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I'm afraid that this executable was compiled before my time here. So I don't have the source code. However, we might be able to use xssp's executable instead and change the whynot code.

**Comment by cbaakman** [comment]
All that whynot checks right now is whether dssp returns the following error message:
"No residues with complete backbone"

All other output from dssp is ignored by the annotater. If a structure is nucleic acids only or carbohydrates only, it will get this information from other sources.

**Comment by jonblack** [comment]
@cbaakman What error does the standard xssp binary give?

**Comment by cbaakman** [comment]
The xssp binary gives "empty protein, or no valid complete residues", while the dsspcmbi binary gives "No residues with complete backbone" for the same input file.

**Comment by jonblack** [comment]
Can whynot just check for that message, or is it too general?

**Comment by cbaakman** [comment]
I think it is: https://github.com/cmbi/whynot/blob/master/annotate.py#L281

**Comment by jonblack** [comment]
So the current whynot doesn't work with dsspcmbi, then? It's actually checking for the output given by the standard xssp?

**Comment by cbaakman** [comment]
Yes, I've replaced it some time ago.
