### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by jonblack** [cmbi/whynot#22]
`compare.py` still reference postgresql even though whynot was migrated to mongo. Is this needed?

There may be other dead code. Check and remove if necessary.

**Comment by cbaakman** [comment]
Yes, tthis looks like an old test script to me. Let's remove it.

**Comment by jonblack** [comment]
Go ahead and remove it. Also check if other files/code can be removed. Make sure you update your fork because I've updated the docker configuration and moved some files around already.

**Comment by jonblack** [comment]
I'm closing this issue because issue #20 will remove the dead code and I'm already quite far with it.
