### ISSUE TITLE
statistics page shows wrong information

### ISSUE THREAD

**Issue by cbaakman** [cmbi/whynot#38]
Several data on the page http://www.cmbi.ru.nl/WHY_NOT2/statistics/ are wrong.

* Most recent annotations shows a list of nulls
* Total number of entries is 248083, too low
* Total number of entries equals total number of annotations
* Most recent files list is empty

**Comment by jonblack** [comment]
I think this was fixed in the commit for #41. There is still information missing, but what's in the database is being displayed correctly as far as I can tell.
