### ISSUE TITLE
crawler re-adds all BDB entries

### ISSUE THREAD

**Issue by cbaakman** [cmbi/whynot#8]
When running, the crawler first removes and then adds all the present bdb entries. A time consuming process. The timestamp check at https://github.com/cmbi/whynot/blob/master/whynot-apps/src/main/java/nl/ru/cmbi/whynot/crawl/Crawler.java#L73 is possibly the cause.

**Comment by jonblack** [comment]
This issue is based on the old java version which no longer exists.
